name: README build
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: readme  # matches where you stored ACCESS_TOKEN & USER_NAME
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - run: python -m pip install -r cache/requirements.txt

      - name: Update README file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   # secret
          USER_NAME:    ${{ vars.USER_NAME }}         # variable
        run: python today.py

      - name: Commit
        run: |
          git add .
          git diff --staged --quiet && echo "No changes" && exit 0
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "Updated README"
          git push

